version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
#installing CircleCI project dependencies
    steps: 
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
#commands to install the frontend and backend
      - run:
          name: install frontend
          command: npm run frontend:install

      - run:
          name: install backend
          command: npm run backend:install
#commands to build the frontend and backend
      - run:
          name: build frontend
          command: npm run frontend:build

      - run:
          name: build backend
          command: npm run backend:build

#send environment variables from CircleCI to Elastic Beanstalk through eb-cli
      - run:
          name: initialize eb
          command: eb init --region $AWS_DEFAULT_REGION udagram-api
      
      - run:
          name: set environment variables
          command: eb setenv AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION = $AWS_DEFAULT_REGION

#commands to deploy the frontend and backend
      - run:
          name: deploy frontend
          command: npm run frontend:deploy

      - run:
          name: deploy backend
          command: npm run backend:deploy
