version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps: 
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - restore-frontend-cache:
          keys:
            - frontend-dependencies-{{checkSum "package.json"}}
            - frontend-dependencies-
      - run:
          name: install frontend
          command: npm run frontend:install
      - save-frontend-cache:
          paths:
            - node_modules
          key: frontend-dependencies-
      - restore-backend-cache:
          keys:
            - backend-dependencies-{{checkSum "package.json"}}
            - backend-dependencies-
      - run:
          name: install backend
          command: npm run backend:install
       save-backend-cache:
          paths:
            - node_modules
          key: backend-dependencies-
      - run:
          name: build frontend
          command: npm run frontend:build
      - run:
          name: build backend
          command: npm run backend:build
      - run:
          name: deploy frontend
          command: npm run frontend:deploy
      - run:
          name: deploy backend
          command: npm run backend:deploy
