version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps: 
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: install frontend
          command: npm run frontend:install
      - run:
          name: install backend
          command: npm run backend:install
      - run:
          name: build frontend
          command: npm run frontend:build
      - run:
          name: build backend
          command: npm run backend:build
      - run:
          name: deploy frontend
          command: npm run frontend:deploy
      - run:
          name: deploy backend
          command: npm run backend:deploy
